name: Go Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Install dependencies
        run: go mod download

      - name: Make build dir
        run: mkdir -p build/ubuntu

      - name: Build for Linux
        run: go build -o build/webcheck

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: build/ubuntu

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update binaries"
          git push origin master

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Make build dir
        run: mkdir -p build/windows
        
      - name: Install dependencies
        run: go mod download

      - name: Build for Windows
        run: go build -o build/webcheck.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: build//windows

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update binaries"
          git push origin master
