name: Go Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Install dependencies
        run: go mod download

      - name: Make build dir
        run: mkdir -p build

      - name: Build for Linux
        run: go build -o build/webcheck

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: build/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Make build dir
        run: mkdir -p build
        
      - name: Install dependencies
        run: go mod download

      - name: Build for Windows
        run: go build -o build/webcheck.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: build/
          
  deploy:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: linux-binary

      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: windows-binary

      - name: Copy binaries to gh-pages
        run: |
          mkdir -p docs/linux
          mkdir -p docs/windows
          cp build/webcheck docs/linux/
          cp build/webcheck.exe docs/windows/

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git commit -m "Update binaries"
          git push origin gh-pages
